const QuizData = [
    {
      id:1,
      question: "You see a non-familiar face in the access-controlled areas of our office, the person does not have the MGL ID/Visitor/Staff/Vendor tag with him. What would you do?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:2,
      question: "What is the capital of Germany?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:3,
      question: "You see a non-familiar face in the access-controlled areas of our office, the person does not have the MGL ID/Visitor/Staff/Vendor tag with him. What would you do?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:4,
      question: "What is the capital of Germany?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:5,
      question: "You see a non-familiar face in the access-controlled areas of our office, the person does not have the MGL ID/Visitor/Staff/Vendor tag with him. What would you do?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:6,
      question: "What is the capital of Germany?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:7,
      question: "You see a non-familiar face in the access-controlled areas of our office, the person does not have the MGL ID/Visitor/Staff/Vendor tag with him. What would you do?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:8,
      question: "What is the capital of Germany?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:9,
      question: "You see a non-familiar face in the access-controlled areas of our office, the person does not have the MGL ID/Visitor/Staff/Vendor tag with him. What would you do?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:10,
      question: "What is the capital of Germany?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:11,
      question: "You see a non-familiar face in the access-controlled areas of our office, the person does not have the MGL ID/Visitor/Staff/Vendor tag with him. What would you do?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:12,
      question: "What is the capital of Germany?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:13,
      question: "You see a non-familiar face in the access-controlled areas of our office, the person does not have the MGL ID/Visitor/Staff/Vendor tag with him. What would you do?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:14,
      question: "What is the capital of Germany?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
    {
      id:15,
      question: "You see a non-familiar face in the access-controlled areas of our office, the person does not have the MGL ID/Visitor/Staff/Vendor tag with him. What would you do?",
      option1:'None of my business, let some body else take care of it',
      option2:'Ask the person to leave the facility',
      option3:'Escort the person to the security and raise a security incident',
      option4:'Raise a security incident and go back doing your work',
      ans:4,
    },
  ];

  export default QuizData;